# YML version
version: "3"

services:
  product-service:
    restart: always
    build: ./product-service
    image: cahyo/product-service:1.0.0
    depends_on:
      - postgres
      - rabbitmq
    environment: # environment variables
      - PORT=3000
      - MQ_HOST=rabbitmq
      - DATABASE_URL=postgres://user:password@postgres:5432/platterDB
    ports:
      - "3000:3000"

  postgres: # PostgreSQL database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=platterDB
    ports:
      - "5432:5432"

  rabbitmq: # rabbitmq
    image: rabbitmq:3.8.9
    logging:
      driver: none
    ports:
      - "5672:5672"
